DROP TABLE rates IF EXISTS;
DROP SEQUENCE global_seq IF EXISTS;

CREATE SEQUENCE GLOBAL_SEQ AS INTEGER START WITH 100000;

CREATE TABLE rates
(
    id               INTEGER GENERATED BY DEFAULT AS SEQUENCE GLOBAL_SEQ PRIMARY KEY,
    user_id          VARCHAR(255)            NOT NULL,
    message_id       VARCHAR(225)            NOT NULL,
    comment          VARCHAR(255),
    marking          BOOLEAN                 NOT NULL,
    date             DATE DEFAULT now()      NOT NULL,
    UNIQUE (user_id, date)
);

CREATE TABLE rates_marks
(
    id               INTEGER GENERATED BY DEFAULT AS SEQUENCE GLOBAL_SEQ PRIMARY KEY,
    rate_id          INTEGER                    NOT NULL,
    mark             VARCHAR(225)               NOT NULL,
    FOREIGN KEY (rate_id) REFERENCES rates (id),
    UNIQUE (rate_id, mark)
)